In [1]:
from pathlib import Path

import pandas as pd

# Step 1: Load this repo's processed generator-level data
base_dir = Path('..')
dispatchable = pd.read_csv(base_dir / 'data/processed/dispatchable_generator_hourly_dataset.csv', parse_dates=['timestamp'])
renewable = pd.read_csv(base_dir / 'data/processed/renewable_generator_hourly_dataset.csv', parse_dates=['timestamp'])

dispatchable_frame = dispatchable.rename(
    columns={
        'timestamp': 'Timestamp',
        'capability_mw': 'Capability',
        'actual_output_mw': 'Output',
        'fuel_type': 'FuelType',
    }
)[['Timestamp', 'generator', 'FuelType', 'Capability', 'Output']]

renewable_frame = renewable.rename(
    columns={
        'timestamp': 'Timestamp',
        'available_capacity': 'Capability',
        'output': 'Output',
        'fuel_type': 'FuelType',
    }
)[['Timestamp', 'generator', 'FuelType', 'Capability', 'Output']]

all_generators = pd.concat([dispatchable_frame, renewable_frame], ignore_index=True)
all_generators['FuelType'] = all_generators['FuelType'].str.upper()

cap = all_generators.pivot_table(index='Timestamp', columns='generator', values='Capability', aggfunc='first').sort_index()
out = all_generators.pivot_table(index='Timestamp', columns='generator', values='Output', aggfunc='first').sort_index()

gen_to_tech = all_generators[['generator', 'FuelType']].drop_duplicates().sort_values('generator').reset_index(drop=True)

In [2]:
cap.head()

generator,ABKENORA,ADELAIDE,AGUASABON,ALEXANDER,AMARANTH,AMHERST ISLAND,APIROQUOIS,ARMOW,ARNPRIOR,ATIKOKAN-G1,...,WELLS,WEST LINCOLN NRWF,WESTWINDSOR,WHITBYCGS,WHITEDOG,WINDSOR AIRPORT SF,WOLFE ISLAND,YORKCGS-G1,YORKCGS-G2,ZURICH
Timestamp,,,,,,,,,,,,,,,,,,,,,
2019-05-01 00:00:00,NaN,60.0,NaN,NaN,199.0,1.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 01:00:00,NaN,60.0,NaN,NaN,199.0,5.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 02:00:00,NaN,60.0,NaN,NaN,199.0,10.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 03:00:00,NaN,60.0,NaN,NaN,199.0,10.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 04:00:00,NaN,60.0,NaN,NaN,199.0,5.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0

In [3]:
gen_to_tech = gen_to_tech.rename(columns={'GeneratorName': 'generator', 'fuel_type': 'FuelType'}).copy()
gen_to_tech['FuelType'] = gen_to_tech['FuelType'].str.upper()
gen_to_tech_dict = dict(zip(gen_to_tech['generator'], gen_to_tech['FuelType']))
print(gen_to_tech_dict)

{'ABKENORA': 'HYDRO', 'ADELAIDE': 'WIND', 'AGUASABON': 'HYDRO', 'ALEXANDER': 'HYDRO', 'AMARANTH': 'WIND', 'AMHERST ISLAND': 'WIND', 'APIROQUOIS': 'HYDRO', 'ARMOW': 'WIND', 'ARNPRIOR': 'HYDRO', 'ATIKOKAN-G1': 'BIOFUEL', 'AUBREYFALLS': 'HYDRO', 'BARRETT': 'HYDRO', 'BECK1': 'HYDRO', 'BECK2': 'HYDRO', 'BECK2 PGS': 'HYDRO', 'BELLE RIVER': 'WIND', 'BLAKE': 'WIND', 'BORNISH': 'WIND', 'BOW LAKE': 'WIND', 'BOW LAKE 2': 'WIND', 'BRIGHTON BEACH': 'GAS', 'BRUCEA-G1': 'NUCLEAR', 'BRUCEA-G2': 'NUCLEAR', 'BRUCEA-G3': 'NUCLEAR', 'BRUCEA-G4': 'NUCLEAR', 'BRUCEB-G5': 'NUCLEAR', 'BRUCEB-G6': 'NUCLEAR', 'BRUCEB-G7': 'NUCLEAR', 'BRUCEB-G8': 'NUCLEAR', 'CALSTOCKGS': 'BIOFUEL', 'CAMERONFALLS': 'HYDRO', 'CANYON': 'HYDRO', 'CARDINAL': 'GAS', 'CARIBOUFALLS': 'HYDRO', 'CARMICHAEL': 'HYDRO', 'CEDAR POINT 2': 'WIND', 'CHATSFALLS': 'HYDRO', 'CHENAUX': 'HYDRO', 'CLERGUE': 'HYDRO', 'COCHRANECGS': 'GAS', 'COMBER': 'WIND', 'CRYSLER': 'WIND', 'DA WATSON': 'HYDRO', 'DARLINGTON-G1': 'NUCLEAR', 'DARLINGTON-G2': 'NUCLEAR', 'DARLINGTON-G3': 'NUCLEAR', 'DARLINGTON-G4': 'NUCLEAR', 'DECEWFALLS': 'HYDRO', 'DECEWND1': 'HYDRO', 'DESJOACHIMS': 'HYDRO', 'DESTEC': 'GAS', 'DILLON': 'WIND', 'DOWCHEMICAL': 'GAS', 'DPNTMTLND': 'GAS', 'EARFALLS': 'HYDRO', 'EAST LAKE': 'WIND', 'EAST WINDSOR-G1': 'GAS', 'EAST WINDSOR-G2': 'GAS', 'ERIEAU': 'WIND', 'FORTFRANCSWC': 'HYDRO', 'GARTSHORE': 'HYDRO', 'GOSFIELDWGS': 'WIND', 'GOSHEN': 'WIND', 'GOULAIS': 'WIND', 'GRAND VALLEY 3': 'WIND', 'GRANDSF': 'SOLAR', 'GRANDWF': 'WIND', 'GREENFIELD ENERGY CENTRE-G1': 'GAS', 'GREENFIELD ENERGY CENTRE-G2': 'GAS', 'GREENFIELD ENERGY CENTRE-G3': 'GAS', 'GREENFIELD ENERGY CENTRE-G4': 'GAS', 'GREENFIELD SOUTH-G1': 'GAS', 'GREENFIELD SOUTH-G2': 'GAS', 'GREENWICH': 'WIND', 'GTAA-G1': 'GAS', 'GTAA-G2': 'GAS', 'GTAA-G3': 'GAS', 'HALTONHILLS-LT.G1': 'GAS', 'HALTONHILLS-LT.G2': 'GAS', 'HALTONHILLS-LT.G3': 'GAS', 'HARMON': 'HYDRO', 'HARMON 2': 'HYDRO', 'HARRIS': 'HYDRO', 'HENVEY NORTH': 'WIND', 'HENVEY SOUTH': 'WIND', 'HOLDEN': 'HYDRO', 'HOLINGSWTH': 'HYDRO', 'HYDROGEN READY POWER PLANT (HRPP)': 'GAS', 'JERICHO': 'WIND', 'K2WIND': 'WIND', 'KAKABEKA': 'HYDRO', 'KAPGS': 'GAS', 'KINGSBRIDGE': 'WIND', 'KINGSTONSF': 'SOLAR', 'KIPLING': 'HYDRO', 'KIPLING 2': 'HYDRO', 'LAKESUPERIOR': 'GAS', 'LANDON': 'WIND', 'LENNOX-G1': 'GAS', 'LENNOX-G2': 'GAS', 'LENNOX-G3': 'GAS', 'LENNOX-G4': 'GAS', 'LITTLELONG': 'HYDRO', 'LITTLELONG 2': 'HYDRO', 'LONGSAULTE': 'HYDRO', 'LOWER WHITE RIVER': 'HYDRO', 'LOWERNOTCH': 'HYDRO', 'MACKAYGS': 'HYDRO', 'MANITOUFALLS': 'HYDRO', 'MCLEANSMTNWF-LT.AG_T1': 'WIND', 'MISSION': 'HYDRO', 'MTNCHUTE': 'HYDRO', 'NAGAGAMI': 'HYDRO', 'NANTICOKE SOLAR': 'SOLAR', 'NAPANEE-G1': 'GAS', 'NAPANEE-G2': 'GAS', 'NAPANEE-G3': 'GAS', 'NIPIGONGS': 'GAS', 'NORTH KENT': 'WIND', 'NORTHBAYGS': 'GAS', 'NORTHLAND POWER SOLAR FACILITIES': 'SOLAR', 'NPIROQFALLS': 'GAS', 'NPKIRKLAND-G1-G5': 'GAS', 'NPKIRKLAND-G6': 'GAS', 'OTTERRAPIDS': 'HYDRO', 'PAROCHES': 'WIND', 'PETER SUTHERLAND SR': 'HYDRO', 'PICKERINGA-G1': 'NUCLEAR', 'PICKERINGA-G4': 'NUCLEAR', 'PICKERINGB-G5': 'NUCLEAR', 'PICKERINGB-G6': 'NUCLEAR', 'PICKERINGB-G7': 'NUCLEAR', 'PICKERINGB-G8': 'NUCLEAR', 'PINEPORTAGE': 'HYDRO', 'PORT BURWELL': 'WIND', 'PORTALMA-T1': 'WIND', 'PORTALMA-T3': 'WIND', 'PORTLANDS-G1': 'GAS', 'PORTLANDS-G2': 'GAS', 'PORTLANDS-G3': 'GAS', 'PRINCEFARM': 'WIND', 'RAILBEDWF-LT.AG_SR': 'WIND', 'RAYNER': 'HYDRO', 'REDROCK': 'HYDRO', 'RIPLEY SOUTH': 'WIND', 'ROMNEY': 'WIND', 'SANDUSK-LT.AG_T1': 'WIND', 'SAUNDERS': 'HYDRO', 'SHANNON': 'WIND', 'SILVERFALLS': 'HYDRO', 'SITHE GOREWAY-G11': 'GAS', 'SITHE GOREWAY-G12': 'GAS', 'SITHE GOREWAY-G13': 'GAS', 'SITHE GOREWAY-G15': 'GAS', 'SMOKY 2': 'HYDRO', 'SOUTHGATE SF': 'SOLAR', 'SPENCE': 'WIND', 'STCLAIRCGS': 'GAS', 'STEEPHILL': 'HYDRO', 'STEWARTVLE': 'HYDRO', 'STONE MILLS SF': 'SOLAR', 'SUMMERHAVEN': 'WIND', 'TAOHSC': 'GAS', 'TASARNIA': 'GAS', 'TAWINDSOR': 'GAS', 'TBAYBOWATER CTS': 'BIOFUEL', 'THOROLDCGS': 'GAS', 'TUNISGS': 'GAS', 'UMBATAFALLS': 'HYDRO', 'UNDERWOOD': 'WIND', 'UPPER WHITE RIVER': 'HYDRO', 'WELLS': 'HYDRO', 'WEST LINCOLN NRWF': 'WIND', 'WESTWINDSOR': 'GAS', 'WHITBYCGS': 'GAS', 'WHITEDOG': 'HYDRO', 'WINDSOR AIRPORT SF': 'SOLAR', 'WOLFE ISLAND': 'WIND', 'YORKCGS-G1': 'GAS', 'YORKCGS-G2': 'GAS', 'ZURICH': 'WIND'}

### Clean generator df's
(ie; HALTONHILLS-LT.G3 vs HALTONHILLS-LT_G3)

In [4]:
def verify_same_generators():
    # Get generator names from each source
    cap_gens = set(cap.columns)
    out_gens = set(out.columns)
    tech_gens = set(gen_to_tech['generator'])

    # Generators in all three files
    common_gens = cap_gens & out_gens & tech_gens

    # Total number in each
    num_cap = len(cap_gens)
    num_out = len(out_gens)
    num_tech = len(tech_gens)
    num_common = len(common_gens)

    # Generators not present in all three
    cap_only = cap_gens - common_gens
    out_only = out_gens - common_gens
    tech_only = tech_gens - common_gens

    # Report
    print("🔍 Generator Matching Summary")
    print(f"Total in capability file:      {num_cap}")
    print(f"Total in output file:          {num_out}")
    print(f"Total in gen_to_tech mapping:  {num_tech}")
    print(f"In all three files:          {num_common}")
    print(f"Not in tech: {len(cap_only)}")

    print("Generators in cap/out only:", cap_only)
    print("Generators in tech only:", tech_only)

verify_same_generators()

🔍 Generator Matching Summary
Total in capability file:      181
Total in output file:          181
Total in gen_to_tech mapping:  181
In all three files:          181
Not in tech: 0
Generators in cap/out only: set()
Generators in tech only: set()

In [5]:
## Manually created from research on generators missing in the generator_to_type.csv file
missing_generator_type_map = {
    'NPCOCHRANE': 'GAS',
    'TADOUGLAS': 'GAS',
}

'''
Drop from out and cap as generators 
-ONEIDA ENERGY STORAGE is a battery storage not a generator so drop to simplify model
-THUNDERBAY-G3 was demolished in 2021 no longer in use
'''
drop_generators_dict = {'ONEIDA ENERGY STORAGE', 'THUNDERBAY-G3'}


## Manually created from comparison of files (perfect overlap between old and new names in timeseries)
rename_map = {
    'HALTONHILLS-LT_G1': 'HALTONHILLS-LT.G1',
    'HALTONHILLS-LT_G2': 'HALTONHILLS-LT.G2',
    'HALTONHILLS-LT_G3': 'HALTONHILLS-LT.G3',
    'RAILBEDWF-LT_AG_SR': 'RAILBEDWF-LT.AG_SR',
    'MCLEANSMTNWF-LT_AG_T1': 'MCLEANSMTNWF-LT.AG_T1',
    'SANDUSK-LT_AG_T1': 'SANDUSK-LT.AG_T1'
    }

def check_timestamp_overlap(df, old_name, new_name):
    if old_name not in df.columns or new_name not in df.columns:
        return None  # One or both names not in DataFrame

    old_times = df[old_name].dropna().index
    new_times = df[new_name].dropna().index
    overlap = old_times.intersection(new_times)
    return len(overlap)

results = []

for old, new in rename_map.items():
    overlap_cap = check_timestamp_overlap(cap, old, new)
    overlap_out = check_timestamp_overlap(out, old, new)
    
    results.append({
        'Old Name': old,
        'New Name': new,
        'Cap Overlap': overlap_cap,
        'Out Overlap': overlap_out,
        'Valid Rename': (overlap_cap == 0 and overlap_out == 0)
    })

df_rename_check = pd.DataFrame(results)
df_rename_check

,Old Name,New Name,Cap Overlap,Out Overlap,Valid Rename
0,HALTONHILLS-LT_G1,HALTONHILLS-LT.G1,None,None,False
1,HALTONHILLS-LT_G2,HALTONHILLS-LT.G2,None,None,False
2,HALTONHILLS-LT_G3,HALTONHILLS-LT.G3,None,None,False
3,RAILBEDWF-LT_AG_SR,RAILBEDWF-LT.AG_SR,None,None,False
4,MCLEANSMTNWF-LT_AG_T1,MCLEANSMTNWF-LT.AG_T1,None,None,False
5,SANDUSK-LT_AG_T1,SANDUSK-LT.AG_T1,None,None,False

In [6]:
# 1. Merge renamed columns in cap and out
def merge_columns(df, rename_map):
    for old, new in rename_map.items():
        if old in df.columns and new in df.columns:
            # Merge values: take non-null values from old, overwrite nulls in new
            df[new] = df[new].combine_first(df[old])
            df.drop(columns=old, inplace=True)
        elif old in df.columns:
            # If new doesn't exist, just rename old to new
            df.rename(columns={old: new}, inplace=True)
    return df

cap = merge_columns(cap, rename_map)
out = merge_columns(out, rename_map)

# 2. Drop unnecessary generators
cap.drop(columns=drop_generators_dict.intersection(cap.columns), inplace=True, errors='ignore')
out.drop(columns=drop_generators_dict.intersection(out.columns), inplace=True, errors='ignore')

# 3. Update the generator-to-tech dictionary directly
# First, recreate the base dictionary from the cleaned DataFrame
gen_to_tech_dict = dict(zip(gen_to_tech['generator'], gen_to_tech['FuelType']))

# Now add missing generators directly to the dictionary
gen_to_tech_dict.update(missing_generator_type_map)

In [7]:
## Verify all generators in out/cap have a "type"
verify_same_generators()

🔍 Generator Matching Summary
Total in capability file:      181
Total in output file:          181
Total in gen_to_tech mapping:  181
In all three files:          181
Not in tech: 0
Generators in cap/out only: set()
Generators in tech only: set()

In [8]:
def trim_generator_data(df):
    trimmed_df = df.copy()
    for col in df.columns:
        series = df[col]
        first_valid = series.first_valid_index()
        last_valid = series.last_valid_index()
        if first_valid is not None and last_valid is not None:
            # Set NaN only *before* and *after* valid data
            trimmed_df.loc[trimmed_df.index < first_valid, col] = pd.NA
            trimmed_df.loc[trimmed_df.index > last_valid, col] = pd.NA
    return trimmed_df

cap = trim_generator_data(cap)
cap = cap.apply(pd.to_numeric, errors='coerce')

out = trim_generator_data(out)
out = out.apply(pd.to_numeric, errors='coerce')

cap.head()

generator,ABKENORA,ADELAIDE,AGUASABON,ALEXANDER,AMARANTH,AMHERST ISLAND,APIROQUOIS,ARMOW,ARNPRIOR,ATIKOKAN-G1,...,WELLS,WEST LINCOLN NRWF,WESTWINDSOR,WHITBYCGS,WHITEDOG,WINDSOR AIRPORT SF,WOLFE ISLAND,YORKCGS-G1,YORKCGS-G2,ZURICH
Timestamp,,,,,,,,,,,,,,,,,,,,,
2019-05-01 00:00:00,NaN,60.0,NaN,NaN,199.0,1.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 01:00:00,NaN,60.0,NaN,NaN,199.0,5.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 02:00:00,NaN,60.0,NaN,NaN,199.0,10.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 03:00:00,NaN,60.0,NaN,NaN,199.0,10.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0
2019-05-01 04:00:00,NaN,60.0,NaN,NaN,199.0,5.0,NaN,180.0,NaN,NaN,...,NaN,230.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,99.0

# Paramaters Estimation

## P_max for each generator

In [9]:
# Compute P_max from capability DataFrame
p_max = cap.max()

# Convert to DataFrame
df_p_max = pd.DataFrame({'P_max': p_max})

# Optional: ensure the generator names are the index
df_p_max.index.name = 'generator'

# Preview the result
df_p_max.head()

           P_max
generator
ABKENORA    11.0
ADELAIDE    60.0
AGUASABON   49.0
ALEXANDER   65.0
AMARANTH   199.0

## P_Min for each generator

In [10]:
import numpy as np
# 1) Replace 0s with NaN to ignore them in min calculation
out_nonzero = out.replace(0, np.nan)

# 2) Compute minimum non-zero output per generator
min_nonzero_output = out_nonzero.min()

# 3) Assemble into a DataFrame
df_min_output = pd.DataFrame({
    'P_min': min_nonzero_output,
})

# Optional: Ensure index order matches original generators
df_min_output = df_min_output.loc[out.columns]

df_min_output.head()

           P_min
generator
ABKENORA     7.0
ADELAIDE     1.0
AGUASABON    1.0
ALEXANDER    1.0
AMARANTH     1.0

## T_up and T_down (minimum time up and down after changing state)


### Estimating $T^U$ and $T^D$ from Historical Generator Output

To assign realistic minimum up-time ($T^U$) and down-time ($T^D$) values for each generator, Analyzed historical hourly output data using the following steps:

---

#### 1. Binary On/Off Classification

Each generator’s output was normalized by its $P^{\max}_g$.
Marked a generator as **on** if its output was ≥ 5% of $P^{\max}_g$; otherwise, it was considered **off**.

---

#### 2. Run-Length Extraction

Parsed each generator’s time series to detect contiguous **on-runs** and **off-runs**, recording their durations.
Runs that began or ended at the edge of the dataset were treated as **censored**.

---

#### 3. Kaplan–Meier Estimation

Used Kaplan–Meier survival curves to model how long generators typically stay on or off.
Defined $T^U$ and $T^D$ as the **5th percentile** of on/off run durations—i.e., the shortest duration seen in at least 95% of cases.

---

#### 4. Outlier Filtering & Tech-Level Smoothing

To avoid overfitting rare behaviors:

* Generators with **too few cycles** (e.g., <30 on-runs) were assigned **tech-level median** values.
* Others kept their individual estimates.

---

#### Final Output

Each generator is assigned a validated $T^U$ and $T^D$, grounded in empirical behavior and smoothed by technology when needed. These values are used directly in the model’s minimum up/down time constraints.

In [11]:
import pandas as pd

# 1) Define on/off as strictly greater than 0
df_onoff = (out > 0).astype(int)  # 1 if output > 0, else 0

# (Optional) Remove this if you're no longer using threshold-based logic
# threshold = 0.05  # Not needed anymore
# p_max_series = p_max if isinstance(p_max, pd.Series) else pd.Series(p_max, index=out.columns)
# on_threshold_mw = p_max_series * threshold

# 2) Function to extract consecutive on/off runs
def extract_runs(binary_series):
    """
    Returns two lists: on_runs and off_runs,
    each a list of (run_length, is_censored)
    """
    runs_on = []
    runs_off = []
    curr_val = binary_series.iloc[0]
    run_len = 1
    for i in range(1, len(binary_series)):
        if binary_series.iloc[i] == curr_val:
            run_len += 1
        else:
            is_censored = False
            if i == len(binary_series) - 1 and curr_val == 1:
                is_censored = True
            if curr_val == 1:
                runs_on.append((run_len, is_censored))
            else:
                runs_off.append((run_len, is_censored))
            curr_val = binary_series.iloc[i]
            run_len = 1
    # Add final run
    if curr_val == 1:
        runs_on.append((run_len, True))
    else:
        runs_off.append((run_len, False))
    return runs_on, runs_off

# 3) Apply run extraction to each generator
on_runs_per_gen = {}
off_runs_per_gen = {}

for gen in df_onoff.columns:
    s = df_onoff[gen].dropna()
    on_runs, off_runs = extract_runs(s)
    on_runs_per_gen[gen] = on_runs
    off_runs_per_gen[gen] = off_runs

In [12]:
import pandas as pd
import numpy as np

# Step 4: KM survival estimator (custom)
def compute_km_survival(durations, event_observed):
    df = pd.DataFrame({'duration': durations, 'event': event_observed})
    df = df.sort_values('duration')
    times = sorted(df['duration'].unique())
    surv = 1.0
    survival = {}
    for t in times:
        d = df[(df['duration'] == t) & (df['event'] == 1)].shape[0]
        at_risk = df[df['duration'] >= t].shape[0]
        if at_risk > 0:
            surv *= (1 - d / at_risk)
        survival[t] = surv
    return survival

# Step 5: Compute T_up and T_down for each generator
results = []
for gen in df_onoff.columns:
    # On-run
    on_runs = on_runs_per_gen.get(gen, [])
    durations_up = [length for length, cens in on_runs]
    events_up    = [int(not cens) for length, cens in on_runs]
    surv_up = compute_km_survival(durations_up, events_up) if durations_up else {}
    T_up = next((t for t, s in surv_up.items() if s <= 0.95), None)
    
    # Off-run
    off_runs = off_runs_per_gen.get(gen, [])
    durations_down = [length for length, cens in off_runs]
    events_down    = [int(not cens) for length, cens in off_runs]
    surv_down = compute_km_survival(durations_down, events_down) if durations_down else {}
    T_down = next((t for t, s in surv_down.items() if s <= 0.95), None)
    
    # Add number of on-runs
    num_on_runs = len(on_runs)
    
    results.append({
        'generator': gen,
        'T_up (hrs)': T_up,
        'T_down (hrs)': T_down,
        'num_on_runs': num_on_runs  # <-- Added
    })

# Step 6: Display results
df_results = pd.DataFrame(results).set_index('generator')

# Cut out any estimates that didnt have enough cycle data
min_cycles = 10
valid = df_results['num_on_runs'] >= min_cycles
df_results.loc[~valid, ['T_up (hrs)', 'T_down (hrs)']] = np.nan
df_results.drop(columns=["num_on_runs"], inplace=True)

In [13]:
pd.set_option("display.max_rows", None)

print(df_results)

                                   T_up (hrs)  T_down (hrs)
generator
ABKENORA                                  NaN           NaN
ADELAIDE                                  1.0           1.0
AGUASABON                                 3.0           1.0
ALEXANDER                                 NaN           NaN
AMARANTH                                  1.0           1.0
AMHERST ISLAND                            1.0           1.0
APIROQUOIS                                NaN           NaN
ARMOW                                     1.0           1.0
ARNPRIOR                                  2.0           1.0
ATIKOKAN-G1                               6.0           4.0
AUBREYFALLS                               1.0           1.0
BARRETT                                   1.0           1.0
BECK1                                     NaN           NaN
BECK2                                     NaN           NaN
BECK2 PGS                                 1.0           1.0
BELLE RIVER                               1.0           1.0
BLAKE                                     1.0           1.0
BORNISH                                   1.0           1.0
BOW LAKE                                  1.0           1.0
BOW LAKE 2                                1.0           1.0
BRIGHTON BEACH                           10.0           1.0
BRUCEA-G1                                 NaN           NaN
BRUCEA-G2                                 NaN           NaN
BRUCEA-G3                                 NaN           NaN
BRUCEA-G4                                 NaN           NaN
BRUCEB-G5                                 NaN           NaN
BRUCEB-G6                                 NaN           NaN
BRUCEB-G7                                 NaN           NaN
BRUCEB-G8                                 NaN           NaN
CALSTOCKGS                                1.0           1.0
CAMERONFALLS                              NaN           NaN
CANYON                                    1.0           1.0
CARDINAL                                 12.0           3.0
CARIBOUFALLS                              3.0           1.0
CARMICHAEL                               23.0           1.0
CEDAR POINT 2                             1.0           1.0
CHATSFALLS                                1.0           1.0
CHENAUX                                   NaN           NaN
CLERGUE                                   NaN           NaN
COCHRANECGS                               3.0           5.0
COMBER                                    1.0           1.0
CRYSLER                                   1.0           1.0
DA WATSON                                 NaN           NaN
DARLINGTON-G1                             NaN           NaN
DARLINGTON-G2                             NaN           NaN
DARLINGTON-G3                             NaN           NaN
DARLINGTON-G4                             NaN           NaN
DECEWFALLS                                2.0           1.0
DECEWND1                                  5.0           1.0
DESJOACHIMS                              19.0           2.0
DESTEC                                    1.0           5.0
DILLON                                    1.0           1.0
DOWCHEMICAL                               NaN           NaN
DPNTMTLND                                 4.0           2.0
EARFALLS                                  NaN           NaN
EAST LAKE                                 1.0           1.0
EAST WINDSOR-G1                           2.0           1.0
EAST WINDSOR-G2                           2.0           1.0
ERIEAU                                    1.0           1.0
FORTFRANCSWC                              NaN           NaN
GARTSHORE                                 1.0           2.0
GOSFIELDWGS                               1.0           1.0
GOSHEN                                    1.0           1.0
GOULAIS                                   1.0           1.0
GRAND VALLEY 3                            1.0           1.0
GRANDSF                                   7.0           9.0
GRANDWF                                   1.0           1.0
GREENFIELD ENERGY CENTRE-G1               6.0           1.0
GREENFIELD ENERGY CENTRE-G2               1.0           2.0
GREENFIELD ENERGY CENTRE-G3               7.0           3.0
GREENFIELD ENERGY CENTRE-G4              11.0           2.0
GREENFIELD SOUTH-G1                       9.0           2.0
GREENFIELD SOUTH-G2                       8.0           2.0
GREENWICH                                 1.0           1.0
GTAA-G1                                   7.0           2.0
GTAA-G2                                   7.0           2.0
GTAA-G3                                   4.0           3.0
HALTONHILLS-LT.G1                         1.0           1.0
HALTONHILLS-LT.G2                         1.0           1.0
HALTONHILLS-LT.G3                         1.0           1.0
HARMON                                    4.0           2.0
HARMON 2                                  1.0           1.0
HARRIS                                  102.0           1.0
HENVEY NORTH                              1.0           1.0
HENVEY SOUTH                              1.0           1.0
HOLDEN                                   21.0           1.0
HOLINGSWTH                                2.0           2.0
HYDROGEN READY POWER PLANT (HRPP)         3.0           1.0
JERICHO                                   1.0           1.0
K2WIND                                    1.0           1.0
KAKABEKA                                  NaN           NaN
KAPGS                                     NaN           NaN
KINGSBRIDGE                               1.0           1.0
KINGSTONSF                                6.0           9.0
KIPLING                                   3.0           1.0
KIPLING 2                                 3.0           2.0
LAKESUPERIOR                              3.0           9.0
LANDON                                    1.0           1.0
LENNOX-G1                                 5.0           5.0
LENNOX-G2                                 5.0           4.0
LENNOX-G3                                 4.0           5.0
LENNOX-G4                                 5.0           5.0
LITTLELONG                                4.0           2.0
LITTLELONG 2                              3.0           3.0
LONGSAULTE                                NaN           NaN
LOWER WHITE RIVER                         2.0           1.0
LOWERNOTCH                                1.0           1.0
MACKAYGS                                  1.0           4.0
MANITOUFALLS                             15.0           1.0
MCLEANSMTNWF-LT.AG_T1                     1.0           1.0
MISSION                                  51.0           1.0
MTNCHUTE                                  2.0           1.0
NAGAGAMI                                  1.0           1.0
NANTICOKE SOLAR                           7.0           8.0
NAPANEE-G1                                9.0           1.0
NAPANEE-G2                                9.0           1.0
NAPANEE-G3                                8.0           2.0
NIPIGONGS                                 NaN           NaN
NORTH KENT                                1.0           1.0
NORTHBAYGS                                1.0           8.0
NORTHLAND POWER SOLAR FACILITIES          4.0           9.0
NPIROQFALLS                               7.0           5.0
NPKIRKLAND-G1-G5                         11.0           2.0
NPKIRKLAND-G6                             1.0           1.0
OTTERRAPIDS                               1.0           1.0
PAROCHES                                  1.0           1.0
PETER SUTHERLAND SR                       2.0           4.0
PICKERINGA-G1                             NaN           NaN
PICKERINGA-G4                             NaN           NaN
PICKERINGB-G5                             NaN           NaN
PICKERINGB-G6                             NaN           NaN
PICKERINGB-G7                             NaN           NaN
PICKERINGB-G8                             NaN           NaN
PINEPORTAGE                               NaN           NaN
PORT BURWELL                              1.0           1.0
PORTALMA-T1                               1.0           1.0
PORTALMA-T3                               1.0           1.0
PORTLANDS-G1                              9.0           2.0
PORTLANDS-G2                              9.0           2.0
PORTLANDS-G3                             11.0           2.0
PRINCEFARM                                1.0           1.0
RAILBEDWF-LT.AG_SR                        1.0           1.0
RAYNER                                    4.0           2.0
REDROCK                                   1.0           2.0
RIPLEY SOUTH                              1.0           1.0
ROMNEY                                    1.0           1.0
SANDUSK-LT.AG_T1                          1.0           1.0
SAUNDERS                                  NaN           NaN
SHANNON                                   1.0           1.0
SILVERFALLS                               2.0           1.0
SITHE GOREWAY-G11                         9.0           1.0
SITHE GOREWAY-G12                         9.0           1.0
SITHE GOREWAY-G13                         8.0           1.0
SITHE GOREWAY-G15                         8.0           2.0
SMOKY 2                                   4.0           2.0
SOUTHGATE SF                              4.0           9.0
SPENCE                                    1.0           1.0
STCLAIRCGS                                8.0           3.0
STEEPHILL                                 1.0           1.0
STEWARTVLE                                2.0           1.0
STONE MILLS SF                            6.0           8.0
SUMMERHAVEN                               1.0           1.0
TAOHSC                                    8.0           3.0
TASARNIA                                  NaN           NaN
TAWINDSOR                                 4.0           4.0
TBAYBOWATER CTS                           1.0           1.0
THOROLDCGS                               10.0           2.0
TUNISGS                                   8.0           7.0
UMBATAFALLS                               NaN           NaN
UNDERWOOD                                 1.0           1.0
UPPER WHITE RIVER                         8.0           1.0
WELLS                                     1.0           1.0
WEST LINCOLN NRWF                         1.0           1.0
WESTWINDSOR                               3.0           2.0
WHITBYCGS                                 NaN           NaN
WHITEDOG                                  1.0           1.0
WINDSOR AIRPORT SF                        6.0          10.0
WOLFE ISLAND                              1.0           1.0
YORKCGS-G1                                3.0           1.0
YORKCGS-G2                                3.0           1.0
ZURICH                                    1.0           1.0

In [14]:
# Step 1: Map each generator to its fuel type
df_results['FuelType'] = df_results.index.map(gen_to_tech_dict)

# Step 2: Compute FuelType-level medians
tech_median_up = df_results.groupby('FuelType')['T_up (hrs)'].median()
tech_median_down = df_results.groupby('FuelType')['T_down (hrs)'].median()

# Step 3: Define adjustment logic (NaNs or extreme outliers get replaced with median)
def adjust_t(row, col, tech_medians):
    val = row[col]
    median = tech_medians.loc[row['FuelType']]
    
    if pd.isna(val):
        return median
    elif val > 1.5 * median:
        return median
    else:
        return val

# Step 4: Apply adjusted values to new columns
df_results['T_up (hrs)'] = df_results.apply(
    lambda r: adjust_t(r, 'T_up (hrs)', tech_median_up), axis=1
)

df_results['T_down (hrs)'] = df_results.apply(
    lambda r: adjust_t(r, 'T_down (hrs)', tech_median_down), axis=1
)

print(df_results)

                                   T_up (hrs)  T_down (hrs) FuelType
generator
ABKENORA                                  2.0           1.0    HYDRO
ADELAIDE                                  1.0           1.0     WIND
AGUASABON                                 3.0           1.0    HYDRO
ALEXANDER                                 2.0           1.0    HYDRO
AMARANTH                                  1.0           1.0     WIND
AMHERST ISLAND                            1.0           1.0     WIND
APIROQUOIS                                2.0           1.0    HYDRO
ARMOW                                     1.0           1.0     WIND
ARNPRIOR                                  2.0           1.0    HYDRO
ATIKOKAN-G1                               1.0           1.0  BIOFUEL
AUBREYFALLS                               1.0           1.0    HYDRO
BARRETT                                   1.0           1.0    HYDRO
BECK1                                     2.0           1.0    HYDRO
BECK2                                     2.0           1.0    HYDRO
BECK2 PGS                                 1.0           1.0    HYDRO
BELLE RIVER                               1.0           1.0     WIND
BLAKE                                     1.0           1.0     WIND
BORNISH                                   1.0           1.0     WIND
BOW LAKE                                  1.0           1.0     WIND
BOW LAKE 2                                1.0           1.0     WIND
BRIGHTON BEACH                           10.0           1.0      GAS
BRUCEA-G1                                 NaN           NaN  NUCLEAR
BRUCEA-G2                                 NaN           NaN  NUCLEAR
BRUCEA-G3                                 NaN           NaN  NUCLEAR
BRUCEA-G4                                 NaN           NaN  NUCLEAR
BRUCEB-G5                                 NaN           NaN  NUCLEAR
BRUCEB-G6                                 NaN           NaN  NUCLEAR
BRUCEB-G7                                 NaN           NaN  NUCLEAR
BRUCEB-G8                                 NaN           NaN  NUCLEAR
CALSTOCKGS                                1.0           1.0  BIOFUEL
CAMERONFALLS                              2.0           1.0    HYDRO
CANYON                                    1.0           1.0    HYDRO
CARDINAL                                  7.0           3.0      GAS
CARIBOUFALLS                              3.0           1.0    HYDRO
CARMICHAEL                                2.0           1.0    HYDRO
CEDAR POINT 2                             1.0           1.0     WIND
CHATSFALLS                                1.0           1.0    HYDRO
CHENAUX                                   2.0           1.0    HYDRO
CLERGUE                                   2.0           1.0    HYDRO
COCHRANECGS                               3.0           2.0      GAS
COMBER                                    1.0           1.0     WIND
CRYSLER                                   1.0           1.0     WIND
DA WATSON                                 2.0           1.0    HYDRO
DARLINGTON-G1                             NaN           NaN  NUCLEAR
DARLINGTON-G2                             NaN           NaN  NUCLEAR
DARLINGTON-G3                             NaN           NaN  NUCLEAR
DARLINGTON-G4                             NaN           NaN  NUCLEAR
DECEWFALLS                                2.0           1.0    HYDRO
DECEWND1                                  2.0           1.0    HYDRO
DESJOACHIMS                               2.0           1.0    HYDRO
DESTEC                                    1.0           2.0      GAS
DILLON                                    1.0           1.0     WIND
DOWCHEMICAL                               7.0           2.0      GAS
DPNTMTLND                                 4.0           2.0      GAS
EARFALLS                                  2.0           1.0    HYDRO
EAST LAKE                                 1.0           1.0     WIND
EAST WINDSOR-G1                           2.0           1.0      GAS
EAST WINDSOR-G2                           2.0           1.0      GAS
ERIEAU                                    1.0           1.0     WIND
FORTFRANCSWC                              2.0           1.0    HYDRO
GARTSHORE                                 1.0           1.0    HYDRO
GOSFIELDWGS                               1.0           1.0     WIND
GOSHEN                                    1.0           1.0     WIND
GOULAIS                                   1.0           1.0     WIND
GRAND VALLEY 3                            1.0           1.0     WIND
GRANDSF                                   7.0           9.0    SOLAR
GRANDWF                                   1.0           1.0     WIND
GREENFIELD ENERGY CENTRE-G1               6.0           1.0      GAS
GREENFIELD ENERGY CENTRE-G2               1.0           2.0      GAS
GREENFIELD ENERGY CENTRE-G3               7.0           3.0      GAS
GREENFIELD ENERGY CENTRE-G4               7.0           2.0      GAS
GREENFIELD SOUTH-G1                       9.0           2.0      GAS
GREENFIELD SOUTH-G2                       8.0           2.0      GAS
GREENWICH                                 1.0           1.0     WIND
GTAA-G1                                   7.0           2.0      GAS
GTAA-G2                                   7.0           2.0      GAS
GTAA-G3                                   4.0           3.0      GAS
HALTONHILLS-LT.G1                         1.0           1.0      GAS
HALTONHILLS-LT.G2                         1.0           1.0      GAS
HALTONHILLS-LT.G3                         1.0           1.0      GAS
HARMON                                    2.0           1.0    HYDRO
HARMON 2                                  1.0           1.0    HYDRO
HARRIS                                    2.0           1.0    HYDRO
HENVEY NORTH                              1.0           1.0     WIND
HENVEY SOUTH                              1.0           1.0     WIND
HOLDEN                                    2.0           1.0    HYDRO
HOLINGSWTH                                2.0           1.0    HYDRO
HYDROGEN READY POWER PLANT (HRPP)         3.0           1.0      GAS
JERICHO                                   1.0           1.0     WIND
K2WIND                                    1.0           1.0     WIND
KAKABEKA                                  2.0           1.0    HYDRO
KAPGS                                     7.0           2.0      GAS
KINGSBRIDGE                               1.0           1.0     WIND
KINGSTONSF                                6.0           9.0    SOLAR
KIPLING                                   3.0           1.0    HYDRO
KIPLING 2                                 3.0           1.0    HYDRO
LAKESUPERIOR                              3.0           2.0      GAS
LANDON                                    1.0           1.0     WIND
LENNOX-G1                                 5.0           2.0      GAS
LENNOX-G2                                 5.0           2.0      GAS
LENNOX-G3                                 4.0           2.0      GAS
LENNOX-G4                                 5.0           2.0      GAS
LITTLELONG                                2.0           1.0    HYDRO
LITTLELONG 2                              3.0           1.0    HYDRO
LONGSAULTE                                2.0           1.0    HYDRO
LOWER WHITE RIVER                         2.0           1.0    HYDRO
LOWERNOTCH                                1.0           1.0    HYDRO
MACKAYGS                                  1.0           1.0    HYDRO
MANITOUFALLS                              2.0           1.0    HYDRO
MCLEANSMTNWF-LT.AG_T1                     1.0           1.0     WIND
MISSION                                   2.0           1.0    HYDRO
MTNCHUTE                                  2.0           1.0    HYDRO
NAGAGAMI                                  1.0           1.0    HYDRO
NANTICOKE SOLAR                           7.0           8.0    SOLAR
NAPANEE-G1                                9.0           1.0      GAS
NAPANEE-G2                                9.0           1.0      GAS
NAPANEE-G3                                8.0           2.0      GAS
NIPIGONGS                                 7.0           2.0      GAS
NORTH KENT                                1.0           1.0     WIND
NORTHBAYGS                                1.0           2.0      GAS
NORTHLAND POWER SOLAR FACILITIES          4.0           9.0    SOLAR
NPIROQFALLS                               7.0           2.0      GAS
NPKIRKLAND-G1-G5                          7.0           2.0      GAS
NPKIRKLAND-G6                             1.0           1.0      GAS
OTTERRAPIDS                               1.0           1.0    HYDRO
PAROCHES                                  1.0           1.0     WIND
PETER SUTHERLAND SR                       2.0           1.0    HYDRO
PICKERINGA-G1                             NaN           NaN  NUCLEAR
PICKERINGA-G4                             NaN           NaN  NUCLEAR
PICKERINGB-G5                             NaN           NaN  NUCLEAR
PICKERINGB-G6                             NaN           NaN  NUCLEAR
PICKERINGB-G7                             NaN           NaN  NUCLEAR
PICKERINGB-G8                             NaN           NaN  NUCLEAR
PINEPORTAGE                               2.0           1.0    HYDRO
PORT BURWELL                              1.0           1.0     WIND
PORTALMA-T1                               1.0           1.0     WIND
PORTALMA-T3                               1.0           1.0     WIND
PORTLANDS-G1                              9.0           2.0      GAS
PORTLANDS-G2                              9.0           2.0      GAS
PORTLANDS-G3                              7.0           2.0      GAS
PRINCEFARM                                1.0           1.0     WIND
RAILBEDWF-LT.AG_SR                        1.0           1.0     WIND
RAYNER                                    2.0           1.0    HYDRO
REDROCK                                   1.0           1.0    HYDRO
RIPLEY SOUTH                              1.0           1.0     WIND
ROMNEY                                    1.0           1.0     WIND
SANDUSK-LT.AG_T1                          1.0           1.0     WIND
SAUNDERS                                  2.0           1.0    HYDRO
SHANNON                                   1.0           1.0     WIND
SILVERFALLS                               2.0           1.0    HYDRO
SITHE GOREWAY-G11                         9.0           1.0      GAS
SITHE GOREWAY-G12                         9.0           1.0      GAS
SITHE GOREWAY-G13                         8.0           1.0      GAS
SITHE GOREWAY-G15                         8.0           2.0      GAS
SMOKY 2                                   2.0           1.0    HYDRO
SOUTHGATE SF                              4.0           9.0    SOLAR
SPENCE                                    1.0           1.0     WIND
STCLAIRCGS                                8.0           3.0      GAS
STEEPHILL                                 1.0           1.0    HYDRO
STEWARTVLE                                2.0           1.0    HYDRO
STONE MILLS SF                            6.0           8.0    SOLAR
SUMMERHAVEN                               1.0           1.0     WIND
TAOHSC                                    8.0           3.0      GAS
TASARNIA                                  7.0           2.0      GAS
TAWINDSOR                                 4.0           2.0      GAS
TBAYBOWATER CTS                           1.0           1.0  BIOFUEL
THOROLDCGS                               10.0           2.0      GAS
TUNISGS                                   8.0           2.0      GAS
UMBATAFALLS                               2.0           1.0    HYDRO
UNDERWOOD                                 1.0           1.0     WIND
UPPER WHITE RIVER                         2.0           1.0    HYDRO
WELLS                                     1.0           1.0    HYDRO
WEST LINCOLN NRWF                         1.0           1.0     WIND
WESTWINDSOR                               3.0           2.0      GAS
WHITBYCGS                                 7.0           2.0      GAS
WHITEDOG                                  1.0           1.0    HYDRO
WINDSOR AIRPORT SF                        6.0          10.0    SOLAR
WOLFE ISLAND                              1.0           1.0     WIND
YORKCGS-G1                                3.0           1.0      GAS
YORKCGS-G2                                3.0           1.0      GAS
ZURICH                                    1.0           1.0     WIND

## Max Up, Max Down

To estimate each generator’s ramp-up and ramp-down limits, we analyzed hourly output data by calculating the change in production between consecutive hours. We considered only the hours where a generator increased or decreased its output, ignoring flat or zero changes.

To reduce the influence of noise or one-off spikes, we used the 95th percentile of all observed positive ramps for each generator. This gives a realistic high-end ramp rate without being overly conservative.

After estimating those empirical ramps, we apply the same physical overrides used in the main UC model:

- nuclear units are set to **60% of rated power per hour**
- hydro units are allowed to move from **0 to Pmax within the hour**

These final ramp rates are used directly in the model’s hourly ramping constraints to ensure operational realism.

In [15]:
import numpy as np
import pandas as pd

# 1) Compute hour-to-hour diffs
diffs = out.diff()

# 2) Extract only true up-ramps (drop zeros & negatives)
diffs_up = diffs.where(diffs > 0, np.nan)

# 3) Compute 95th percentile of those positive ramps
ramp_up = diffs_up.quantile(0.95)

# 4) Likewise for down-ramps: flip sign, keep only negatives
diffs_down = diffs.where(diffs < 0, np.nan)
ramp_down = (-diffs_down).quantile(0.95)

# 5) Combine into a DataFrame
df_ramps = pd.DataFrame({
    'Ramp Up (MW/hr)':   ramp_up,
    'Ramp Down (MW/hr)': ramp_down
})

# Ensure the order matches `out.columns`
df_ramps = df_ramps.loc[out.columns]

# Apply the physical overrides used in the main UC model
fuel_type = pd.Series(gen_to_tech_dict).reindex(df_ramps.index).str.upper()
p_max_series = df_p_max['P_max'].reindex(df_ramps.index)

nuclear_mask = fuel_type.eq('NUCLEAR')
hydro_mask = fuel_type.eq('HYDRO')

df_ramps.loc[nuclear_mask, 'Ramp Up (MW/hr)'] = 0.60 * p_max_series[nuclear_mask]
df_ramps.loc[nuclear_mask, 'Ramp Down (MW/hr)'] = 0.60 * p_max_series[nuclear_mask]

df_ramps.loc[hydro_mask, 'Ramp Up (MW/hr)'] = p_max_series[hydro_mask]
df_ramps.loc[hydro_mask, 'Ramp Down (MW/hr)'] = p_max_series[hydro_mask]

df_ramps.head()

           Ramp Up (MW/hr)  Ramp Down (MW/hr)
generator
ABKENORA              11.0               11.0
ADELAIDE              20.0               19.0
AGUASABON             49.0               49.0
ALEXANDER             65.0               65.0
AMARANTH              31.0               30.0

## Startup Cost and Shutdown Cost

In [16]:
import pandas as pd

# Assumed inputs as DataFrames:
# 1) p_min_df: DataFrame with a column 'P_min', indexed by generator ID
# 2) ramp_df:  DataFrame with columns 'Ramp Up (MW/hr)' and 'Ramp Down (MW/hr)', indexed by generator ID
# 3) C_V:      dict or Series mapping technology → variable cost ($/MWh)
# 4) gen_to_tech: dict mapping generator ID → technology key

C_V = {
    'GAS': 6.3364,
    'NUCLEAR': 2.852,
    'HYDRO': 0,
    'WIND': 0,
    'SOLAR': 0,
    'BIOFUEL': 5.208
}

# Extract Series from DataFrames
p_min = df_min_output['P_min']
p_max = df_p_max['P_max']
p_reg = (p_min + p_max) / 2 


ramp_up = df_ramps['Ramp Up (MW/hr)']
ramp_down = df_ramps['Ramp Down (MW/hr)']

# 1) Compute implied startup/shutdown durations (hours)
T_startup  = p_reg / ramp_up
T_shutdown = p_reg / ramp_down

# 2) Compute energy consumed during ramp (MWh)
#    Assume linear ramp: average output = P_min / 2
E_startup  = 0.5 * p_reg * T_startup
E_shutdown = 0.5 * p_reg * T_shutdown

# 3) Compute costs ($)
startup_cost = pd.Series(index=p_reg.index, dtype=float)
shutdown_cost = pd.Series(index=p_reg.index, dtype=float)
var_cost = pd.Series(index=p_reg.index, dtype=float)

for gen in p_reg.index:
    tech = gen_to_tech_dict[gen]
    Cv   = C_V[tech]
    startup_cost[gen]  = Cv * E_startup.loc[gen]
    shutdown_cost[gen] = Cv * E_shutdown.loc[gen]
    var_cost[gen] = Cv

# 4) Combine into one DataFrame for clarity
cost_df = pd.DataFrame({
    'T_startup (h)':      T_startup,
    'T_shutdown (h)':     T_shutdown,
    'E_startup (MWh)':    E_startup,
    'E_shutdown (MWh)':   E_shutdown,
    'Cost_startup ($)':   startup_cost,
    'Cost_shutdown ($)':  shutdown_cost,
    'Cost_variable ($/MWh)': var_cost
})


cost_df

/var/folders/gc/2hjqw94d0fg3h32mgnj49r7m0000gn/T/ipykernel_57590/886492729.py:44: RuntimeWarning: invalid value encountered in scalar multiply
  startup_cost[gen]  = Cv * E_startup.loc[gen]
/var/folders/gc/2hjqw94d0fg3h32mgnj49r7m0000gn/T/ipykernel_57590/886492729.py:45: RuntimeWarning: invalid value encountered in scalar multiply
  shutdown_cost[gen] = Cv * E_shutdown.loc[gen]

,T_startup (h),T_shutdown (h),E_startup (MWh),E_shutdown (MWh),Cost_startup ($),Cost_shutdown ($),Cost_variable ($/MWh)
generator,,,,,,,
ABKENORA,0.818182,0.818182,3.681818,3.681818,0.000000,0.000000,0.0000
ADELAIDE,1.525000,1.605263,23.256250,24.480263,0.000000,0.000000,0.0000
AGUASABON,0.510204,0.510204,6.377551,6.377551,0.000000,0.000000,0.0000
ALEXANDER,0.507692,0.507692,8.376923,8.376923,0.000000,0.000000,0.0000
AMARANTH,3.225806,3.333333,161.290323,166.666667,0.000000,0.000000,0.0000
AMHERST ISLAND,1.562500,1.704545,29.296875,31.960227,0.000000,0.000000,0.0000
APIROQUOIS,0.546610,0.546610,17.628178,17.628178,0.000000,0.000000,0.0000
ARMOW,1.740385,1.774510,78.752404,80.296569,0.000000,0.000000,0.0000
ARNPRIOR,0.506098,0.506098,10.501524,10.501524,0.000000,0.000000,0.0000
ATIKOKAN-G1,2.287500,1.641256,104.653125,75.087444,545.033475,391.055408,5.2080
AUBREYFALLS,0.503425,0.503425,18.500856,18.500856,0.000000,0.000000,0.0000
BARRETT,0.502841,0.502841,22.250710,22.250710,0.000000,0.000000,0.0000
BECK1,0.500894,0.500894,70.125224,70.125224,0.000000,0.000000,0.0000
BECK2,0.726450,0.726450,422.975749,422.975749,0.000000,0.000000,0.0000
BECK2 PGS,0.504310,0.504310,14.751078,14.751078,0.000000,0.000000,0.0000
BELLE RIVER,1.683333,1.803571,42.504167,45.540179,0.000000,0.000000,0.0000
BLAKE,1.525000,1.525000,23.256250,23.256250,0.000000,0.000000,0.0000
BORNISH,1.608696,1.608696,29.760870,29.760870,0.000000,0.000000,0.0000
BOW LAKE,1.750000,1.500000,9.187500,7.875000,0.000000,0.000000,0.0000
BOW LAKE 2,1.863636,1.863636,19.102273,19.102273,0.000000,0.000000,0.0000
BRIGHTON BEACH,2.080233,1.806180,334.397444,290.343399,2118.875965,1839.731913,6.3364
BRUCEA-G1,0.837359,0.837359,174.170692,174.170692,496.734815,496.734815,2.8520
BRUCEA-G2,0.839372,0.839372,175.009058,175.009058,499.125833,499.125833,2.8520
BRUCEA-G3,NaN,NaN,NaN,NaN,NaN,NaN,2.8520
BRUCEA-G4,0.844567,0.844567,174.614226,174.614226,497.999772,497.999772,2.8520
BRUCEB-G5,0.841493,0.841493,173.557987,173.557987,494.987378,494.987378,2.8520
BRUCEB-G6,0.940432,0.940432,216.769686,216.769686,618.227144,618.227144,2.8520
BRUCEB-G7,0.834353,0.834353,170.625255,170.625255,486.623227,486.623227,2.8520
BRUCEB-G8,0.834353,0.834353,170.625255,170.625255,486.623227,486.623227,2.8520
CALSTOCKGS,2.166667,2.166667,21.125000,21.125000,110.019000,110.019000,5.2080
CAMERONFALLS,0.557292,0.557292,14.907552,14.907552,0.000000,0.000000,0.0000
CANYON,0.501437,0.501437,43.750359,43.750359,0.000000,0.000000,0.0000
CARDINAL,1.594828,0.925000,73.760776,42.781250,467.377780,271.079113,6.3364
CARIBOUFALLS,0.505319,0.505319,12.001330,12.001330,0.000000,0.000000,0.0000
CARMICHAEL,0.526316,0.526316,2.631579,2.631579,0.000000,0.000000,0.0000
CEDAR POINT 2,1.442857,1.530303,36.432143,38.640152,0.000000,0.000000,0.0000
CHATSFALLS,0.502604,0.502604,24.250651,24.250651,0.000000,0.000000,0.0000
CHENAUX,0.557823,0.557823,22.870748,22.870748,0.000000,0.000000,0.0000
CLERGUE,0.509434,0.509434,6.877358,6.877358,0.000000,0.000000,0.0000
COCHRANECGS,0.186567,0.108696,0.233209,0.135870,1.477705,0.860924,6.3364
COMBER,2.256757,2.455882,94.219595,102.533088,0.000000,0.000000,0.0000
CRYSLER,1.803571,2.020000,45.540179,51.005000,0.000000,0.000000,0.0000
DA WATSON,0.506250,0.506250,10.251563,10.251563,0.000000,0.000000,0.0000
DARLINGTON-G1,0.858872,0.858872,194.964056,194.964056,556.037488,556.037488,2.8520
DARLINGTON-G2,1.586266,1.586266,665.041856,665.041856,1896.699373,1896.699373,2.8520
DARLINGTON-G3,0.846576,0.846576,189.421349,189.421349,540.229687,540.229687,2.8520
DARLINGTON-G4,NaN,NaN,NaN,NaN,NaN,NaN,2.8520
DECEWFALLS,0.503378,0.503378,18.750845,18.750845,0.000000,0.000000,0.0000
DECEWND1,0.517241,0.517241,3.879310,3.879310,0.000000,0.000000,0.0000
DESJOACHIMS,0.501166,0.501166,53.875291,53.875291,0.000000,0.000000,0.0000
DESTEC,1.447368,0.728916,43.782895,22.049699,277.425934,139.715711,6.3364
DILLON,2.078947,2.323529,41.059211,45.889706,0.000000,0.000000,0.0000
DOWCHEMICAL,6.166667,6.166667,57.041667,57.041667,361.438817,361.438817,6.3364
DPNTMTLND,1.204545,1.104167,15.960227,14.630208,101.130384,92.702852,6.3364
EARFALLS,0.527778,0.527778,2.506944,2.506944,0.000000,0.000000,0.0000
EAST LAKE,2.173913,2.380952,54.347826,59.523810,0.000000,0.000000,0.0000
EAST WINDSOR-G1,0.631720,0.618421,7.422715,7.266447,47.033292,46.043117,6.3364
EAST WINDSOR-G2,0.671429,0.652778,7.889286,7.670139,49.989670,48.601068,6.3364
ERIEAU,2.272727,2.380952,56.818182,59.523810,0.000000,0.000000,0.0000
FORTFRANCSWC,0.550000,0.550000,1.512500,1.512500,0.000000,0.000000,0.0000
GARTSHORE,0.505618,0.505618,11.376404,11.376404,0.000000,0.000000,0.0000
GOSFIELDWGS,2.166667,2.363636,28.166667,30.727273,0.000000,0.000000,0.0000
GOSHEN,1.661290,1.716667,42.778226,44.204167,0.000000,0.000000,0.0000
GOULAIS,1.857143,1.857143,12.071429,12.071429,0.000000,0.000000,0.0000
GRAND VALLEY 3,2.050000,2.277778,21.012500,23.347222,0.000000,0.000000,0.0000
GRANDSF,1.485294,1.485294,37.503676,37.503676,0.000000,0.000000,0.0000
GRANDWF,1.704545,1.973684,63.920455,74.013158,0.000000,0.000000,0.0000
GREENFIELD ENERGY CENTRE-G1,2.244444,2.472460,113.344444,124.859241,718.195738,791.158095,6.3364
GREENFIELD ENERGY CENTRE-G2,2.463415,2.805556,124.402439,141.680556,788.263615,897.744672,6.3364
GREENFIELD ENERGY CENTRE-G3,2.589744,2.885714,130.782051,145.728571,828.687390,923.394520,6.3364
GREENFIELD ENERGY CENTRE-G4,2.891986,2.648936,360.052265,329.792553,2281.435171,2089.697534,6.3364
GREENFIELD SOUTH-G1,1.507812,0.984694,72.751953,47.511480,460.985476,301.051739,6.3364
GREENFIELD SOUTH-G2,1.717949,1.116667,57.551282,37.408333,364.667944,237.034163,6.3364
GREENWICH,2.173913,2.173913,54.347826,54.347826,0.000000,0.000000,0.0000
GTAA-G1,0.857143,0.827586,10.285714,9.931034,65.174400,62.927007,6.3364
GTAA-G2,0.857143,0.827586,10.285714,9.931034,65.174400,62.927007,6.3364
GTAA-G3,0.033333,0.029412,0.008333,0.007353,0.052803,0.046591,6.3364
HALTONHILLS-LT.G1,1.837709,1.256117,106.127685,72.540783,672.467463,459.647418,6.3364
HALTONHILLS-LT.G2,1.862903,1.450094,107.582661,83.742938,681.686775,530.628751,6.3364
HALTONHILLS-LT.G3,1.973684,1.726122,148.026316,129.459148,937.953947,820.304948,6.3364
HARMON,0.503205,0.503205,19.750801,19.750801,0.000000,0.000000,0.0000
HARMON 2,0.506410,0.506410,10.001603,10.001603,0.000000,0.000000,0.0000
HARRIS,0.541667,0.541667,1.760417,1.760417,0.000000,0.000000,0.0000
HENVEY NORTH,1.735294,1.843750,51.191176,54.390625,0.000000,0.000000,0.0000
HENVEY SOUTH,1.840000,1.957447,84.640000,90.042553,0.000000,0.000000,0.0000
HOLDEN,0.501887,0.501887,33.375472,33.375472,0.000000,0.000000,0.0000
HOLINGSWTH,0.521739,0.521739,3.130435,3.130435,0.000000,0.000000,0.0000
HYDROGEN READY POWER PLANT (HRPP),0.704082,0.623494,36.436224,32.265813,230.874493,204.449099,6.3364
JERICHO,1.704545,1.785714,63.920455,66.964286,0.000000,0.000000,0.0000
K2WIND,1.806667,1.856164,122.401667,125.755137,0.000000,0.000000,0.0000
KAKABEKA,0.520000,0.520000,3.380000,3.380000,0.000000,0.000000,0.0000
KAPGS,1.713483,1.270833,26.130618,19.380208,165.574048,122.800752,6.3364
KINGSBRIDGE,2.277778,2.277778,23.347222,23.347222,0.000000,0.000000,0.0000
KINGSTONSF,1.530303,1.578125,38.640152,39.847656,0.000000,0.000000,0.0000
KIPLING,0.503289,0.503289,19.250822,19.250822,0.000000,0.000000,0.0000
KIPLING 2,0.506329,0.506329,10.126582,10.126582,0.000000,0.000000,0.0000
LAKESUPERIOR,1.702703,1.549815,53.635135,48.819188,339.853670,309.337904,6.3364
LANDON,1.366667,1.464286,14.008333,15.008929,0.000000,0.000000,0.0000
LENNOX-G1,2.573386,2.656566,338.400196,349.338384,2144.239000,2213.547735,6.3364
LENNOX-G2,2.236395,2.169967,294.085884,285.350660,1863.445798,1808.095922,6.3364
LENNOX-G3,2.678208,2.347166,352.184318,308.652387,2231.580711,1955.744987,6.3364
LENNOX-G4,2.793415,2.386570,367.334041,313.833938,2327.575420,1988.577367,6.3364
LITTLELONG,0.503472,0.503472,18.250868,18.250868,0.000000,0.000000,0.0000
LITTLELONG 2,0.506667,0.506667,9.626667,9.626667,0.000000,0.000000,0.0000
LONGSAULTE,0.550000,0.550000,3.025000,3.025000,0.000000,0.000000,0.0000
LOWER WHITE RIVER,1.000000,1.000000,0.500000,0.500000,0.000000,0.000000,0.0000
LOWERNOTCH,0.501825,0.501825,34.500456,34.500456,0.000000,0.000000,0.0000
MACKAYGS,0.508065,0.508065,8.002016,8.002016,0.000000,0.000000,0.0000
MANITOUFALLS,0.506757,0.506757,9.501689,9.501689,0.000000,0.000000,0.0000
MCLEANSMTNWF-LT.AG_T1,2.346154,2.541667,35.778846,38.760417,0.000000,0.000000,0.0000
MISSION,0.533333,0.533333,2.133333,2.133333,0.000000,0.000000,0.0000
MTNCHUTE,0.502890,0.502890,21.875723,21.875723,0.000000,0.000000,0.0000
NAGAGAMI,0.527778,0.527778,2.506944,2.506944,0.000000,0.000000,0.0000
NANTICOKE SOLAR,1.406250,1.406250,15.820312,15.820312,0.000000,0.000000,0.0000
NAPANEE-G1,1.717105,1.535294,112.041118,100.177941,709.937343,634.767506,6.3364
NAPANEE-G2,1.763514,1.463825,115.069257,95.514582,729.124839,605.218598,6.3364
NAPANEE-G3,1.944915,1.765385,223.179025,202.577885,1414.151577,1283.614508,6.3364
NIPIGONGS,NaN,NaN,NaN,NaN,NaN,NaN,6.3364
NORTH KENT,1.724138,1.724138,43.103448,43.103448,0.000000,0.000000,0.0000
NORTHBAYGS,2.033333,1.540404,31.008333,23.491162,196.481203,148.849396,6.3364
NORTHLAND POWER SOLAR FACILITIES,1.366667,1.366667,14.008333,14.008333,0.000000,0.000000,0.0000
NPIROQFALLS,1.351931,0.840000,42.585837,26.460000,269.840897,167.661144,6.3364
NPKIRKLAND-G1-G5,1.812500,1.312217,39.421875,28.540724,249.792769,180.845443,6.3364
NPKIRKLAND-G6,0.708333,0.653846,6.020833,5.557692,38.150408,35.215762,6.3364
OTTERRAPIDS,0.502439,0.502439,25.875610,25.875610,0.000000,0.000000,0.0000
PAROCHES,1.923077,2.083333,24.038462,26.041667,0.000000,0.000000,0.0000
PETER SUTHERLAND SR,0.518519,0.518519,3.629630,3.629630,0.000000,0.000000,0.0000
PICKERINGA-G1,NaN,NaN,NaN,NaN,NaN,NaN,2.8520
PICKERINGA-G4,NaN,NaN,NaN,NaN,NaN,NaN,2.8520
PICKERINGB-G5,0.850629,0.850629,115.047563,115.047563,328.115649,328.115649,2.8520
PICKERINGB-G6,0.834942,0.834942,108.333736,108.333736,308.967814,308.967814,2.8520
PICKERINGB-G7,0.871069,0.871069,120.643082,120.643082,344.074069,344.074069,2.8520
PICKERINGB-G8,1.552445,1.552445,374.527429,374.527429,1068.152228,1068.152228,2.8520
PINEPORTAGE,0.503425,0.503425,18.500856,18.500856,0.000000,0.000000,0.0000
PORT BURWELL,1.923077,2.083333,48.076923,52.083333,0.000000,0.000000,0.0000
PORTALMA-T1,2.040000,2.217391,52.020000,56.543478,0.000000,0.000000,0.0000
PORTALMA-T3,1.961538,2.040000,50.019231,52.020000,0.000000,0.000000,0.0000
PORTLANDS-G1,1.316456,1.125541,68.455696,58.528139,433.762673,370.857697,6.3364
PORTLANDS-G2,1.791667,1.679688,96.302083,90.283203,610.208521,572.070488,6.3364
PORTLANDS-G3,1.948276,1.738462,110.077586,98.223077,697.495617,622.380705,6.3364
PRINCEFARM,2.638889,2.794118,125.347222,132.720588,0.000000,0.000000,0.0000
RAILBEDWF-LT.AG_SR,1.881944,2.022388,127.501736,137.016791,0.000000,0.000000,0.0000
RAYNER,0.511905,0.511905,5.502976,5.502976,0.000000,0.000000,0.0000
REDROCK,0.510417,0.510417,6.252604,6.252604,0.000000,0.000000,0.0000
RIPLEY SOUTH,2.026316,2.138889,39.006579,41.173611,0.000000,0.000000,0.0000
ROMNEY,1.605263,1.694444,24.480263,25.840278,0.000000,0.000000,0.0000
SANDUSK-LT.AG_T1,2.100000,2.282609,55.125000,59.918478,0.000000,0.000000,0.0000
SAUNDERS,0.632622,0.632622,196.903582,196.903582,0.000000,0.000000,0.0000
SHANNON,2.421053,2.555556,55.684211,58.777778,0.000000,0.000000,0.0000
SILVERFALLS,0.509804,0.509804,6.627451,6.627451,0.000000,0.000000,0.0000
SITHE GOREWAY-G11,1.058648,1.086735,56.373012,57.868622,357.201953,366.678739,6.3364
SITHE GOREWAY-G12,1.065000,1.109375,56.711250,59.074219,359.345165,374.317880,6.3364
SITHE GOREWAY-G13,1.065000,1.132979,56.711250,60.331117,359.345165,382.282090,6.3364
SITHE GOREWAY-G15,1.994318,1.687500,175.001420,148.078125,1108.879001,938.282231,6.3364
SMOKY 2,0.501880,0.501880,33.500470,33.500470,0.000000,0.000000,0.0000
SOUTHGATE SF,1.700000,1.700000,21.675000,21.675000,0.000000,0.000000,0.0000
SPENCE,1.785714,1.851852,44.642857,46.296296,0.000000,0.000000,0.0000
STCLAIRCGS,1.738764,1.703357,269.073736,263.594524,1704.958821,1670.240341,6.3364
STEEPHILL,0.533333,0.533333,2.133333,2.133333,0.000000,0.000000,0.0000
STEWARTVLE,0.502747,0.502747,23.000687,23.000687,0.000000,0.000000,0.0000
STONE MILLS SF,1.375000,1.375000,18.906250,18.906250,0.000000,0.000000,0.0000
SUMMERHAVEN,1.838235,2.016129,57.444853,63.004032,0.000000,0.000000,0.0000
TAOHSC,1.543478,0.633929,27.396739,11.252232,173.596698,71.298644,6.3364
TASARNIA,2.750000,2.765027,347.875000,349.775956,2204.275150,2216.320369,6.3364
TAWINDSOR,1.425926,0.770771,27.449074,14.837337,173.928313,94.015304,6.3364
TBAYBOWATER CTS,2.125000,1.961538,27.093750,25.009615,141.104250,130.250077,5.2080
THOROLDCGS,1.887027,1.576763,143.414029,119.834025,908.728651,759.316315,6.3364
TUNISGS,0.909091,0.937500,13.636364,14.062500,86.405455,89.105625,6.3364
UMBATAFALLS,0.520833,0.520833,3.255208,3.255208,0.000000,0.000000,0.0000
UNDERWOOD,2.472973,2.472973,113.138514,113.138514,0.000000,0.000000,0.0000
UPPER WHITE RIVER,inf,inf,inf,inf,NaN,NaN,0.0000
WELLS,0.502212,0.502212,28.500553,28.500553,0.000000,0.000000,0.0000
WEST LINCOLN NRWF,2.062500,2.264706,119.109375,130.786765,0.000000,0.000000,0.0000
WESTWINDSOR,1.636364,1.180328,58.909091,42.491803,373.271564,269.245062,6.3364
WHITBYCGS,NaN,NaN,NaN,NaN,NaN,NaN,6.3364
WHITEDOG,0.507353,0.507353,8.751838,8.751838,0.000000,0.000000,0.0000
WINDSOR AIRPORT SF,1.700000,1.700000,21.675000,21.675000,0.000000,0.000000,0.0000
WOLFE ISLAND,2.163043,2.426829,107.611413,120.734756,0.000000,0.000000,0.0000
YORKCGS-G1,0.794837,0.866667,46.497962,50.700000,294.629686,321.255480,6.3364
YORKCGS-G2,0.841727,0.854015,49.241007,49.959854,312.010718,316.565619,6.3364
ZURICH,1.923077,2.000000,48.076923,50.000000,0.000000,0.000000,0.0000

## Variable Cost

In [17]:
C_V = {
    'GAS': 6.3364,
    'NUCLEAR': 2.852,
    'HYDRO': 0,
    'WIND': 0,
    'SOLAR': 0,
    'BIOFUEL': 5.208
}

## Generator Commision date

In [18]:
def get_commission_year_df(df):
    """
    Given a DataFrame with timestamps as index and generator names as columns,
    returns a DataFrame with each generator's commission year.
    """
    commission_years = {}
    for gen in df.columns:
        first_valid = df[gen].first_valid_index()
        if first_valid is not None:
            commission_years[gen] = first_valid.year
        else:
            commission_years[gen] = None
    return pd.DataFrame.from_dict(commission_years, orient='index', columns=['commission_year'])

commission_year_df = get_commission_year_df(cap)
print(commission_year_df)

                                   commission_year
ABKENORA                                      2025
ADELAIDE                                      2019
AGUASABON                                     2025
ALEXANDER                                     2025
AMARANTH                                      2019
AMHERST ISLAND                                2019
APIROQUOIS                                    2025
ARMOW                                         2019
ARNPRIOR                                      2025
ATIKOKAN-G1                                   2025
AUBREYFALLS                                   2025
BARRETT                                       2025
BECK1                                         2025
BECK2                                         2025
BECK2 PGS                                     2025
BELLE RIVER                                   2019
BLAKE                                         2019
BORNISH                                       2019
BOW LAKE                                      2019
BOW LAKE 2                                    2019
BRIGHTON BEACH                                2025
BRUCEA-G1                                     2025
BRUCEA-G2                                     2025
BRUCEA-G3                                     2025
BRUCEA-G4                                     2025
BRUCEB-G5                                     2025
BRUCEB-G6                                     2025
BRUCEB-G7                                     2025
BRUCEB-G8                                     2025
CALSTOCKGS                                    2025
CAMERONFALLS                                  2025
CANYON                                        2025
CARDINAL                                      2025
CARIBOUFALLS                                  2025
CARMICHAEL                                    2025
CEDAR POINT 2                                 2019
CHATSFALLS                                    2025
CHENAUX                                       2025
CLERGUE                                       2025
COCHRANECGS                                   2025
COMBER                                        2019
CRYSLER                                       2019
DA WATSON                                     2025
DARLINGTON-G1                                 2025
DARLINGTON-G2                                 2025
DARLINGTON-G3                                 2025
DARLINGTON-G4                                 2025
DECEWFALLS                                    2025
DECEWND1                                      2025
DESJOACHIMS                                   2025
DESTEC                                        2025
DILLON                                        2019
DOWCHEMICAL                                   2025
DPNTMTLND                                     2025
EARFALLS                                      2025
EAST LAKE                                     2019
EAST WINDSOR-G1                               2025
EAST WINDSOR-G2                               2025
ERIEAU                                        2019
FORTFRANCSWC                                  2025
GARTSHORE                                     2025
GOSFIELDWGS                                   2019
GOSHEN                                        2019
GOULAIS                                       2019
GRAND VALLEY 3                                2019
GRANDSF                                       2019
GRANDWF                                       2019
GREENFIELD ENERGY CENTRE-G1                   2025
GREENFIELD ENERGY CENTRE-G2                   2025
GREENFIELD ENERGY CENTRE-G3                   2025
GREENFIELD ENERGY CENTRE-G4                   2025
GREENFIELD SOUTH-G1                           2025
GREENFIELD SOUTH-G2                           2025
GREENWICH                                     2019
GTAA-G1                                       2025
GTAA-G2                                       2025
GTAA-G3                                       2025
HALTONHILLS-LT.G1                             2025
HALTONHILLS-LT.G2                             2025
HALTONHILLS-LT.G3                             2025
HARMON                                        2025
HARMON 2                                      2025
HARRIS                                        2025
HENVEY NORTH                                  2019
HENVEY SOUTH                                  2019
HOLDEN                                        2025
HOLINGSWTH                                    2025
HYDROGEN READY POWER PLANT (HRPP)             2025
JERICHO                                       2019
K2WIND                                        2019
KAKABEKA                                      2025
KAPGS                                         2025
KINGSBRIDGE                                   2019
KINGSTONSF                                    2019
KIPLING                                       2025
KIPLING 2                                     2025
LAKESUPERIOR                                  2025
LANDON                                        2019
LENNOX-G1                                     2025
LENNOX-G2                                     2025
LENNOX-G3                                     2025
LENNOX-G4                                     2025
LITTLELONG                                    2025
LITTLELONG 2                                  2025
LONGSAULTE                                    2025
LOWER WHITE RIVER                             2025
LOWERNOTCH                                    2025
MACKAYGS                                      2025
MANITOUFALLS                                  2025
MCLEANSMTNWF-LT.AG_T1                         2019
MISSION                                       2025
MTNCHUTE                                      2025
NAGAGAMI                                      2025
NANTICOKE SOLAR                               2019
NAPANEE-G1                                    2025
NAPANEE-G2                                    2025
NAPANEE-G3                                    2025
NIPIGONGS                                     2025
NORTH KENT                                    2019
NORTHBAYGS                                    2025
NORTHLAND POWER SOLAR FACILITIES              2019
NPIROQFALLS                                   2025
NPKIRKLAND-G1-G5                              2025
NPKIRKLAND-G6                                 2025
OTTERRAPIDS                                   2025
PAROCHES                                      2019
PETER SUTHERLAND SR                           2025
PICKERINGA-G1                                 2025
PICKERINGA-G4                                 2025
PICKERINGB-G5                                 2025
PICKERINGB-G6                                 2025
PICKERINGB-G7                                 2025
PICKERINGB-G8                                 2025
PINEPORTAGE                                   2025
PORT BURWELL                                  2019
PORTALMA-T1                                   2019
PORTALMA-T3                                   2019
PORTLANDS-G1                                  2025
PORTLANDS-G2                                  2025
PORTLANDS-G3                                  2025
PRINCEFARM                                    2019
RAILBEDWF-LT.AG_SR                            2019
RAYNER                                        2025
REDROCK                                       2025
RIPLEY SOUTH                                  2019
ROMNEY                                        2019
SANDUSK-LT.AG_T1                              2019
SAUNDERS                                      2025
SHANNON                                       2019
SILVERFALLS                                   2025
SITHE GOREWAY-G11                             2025
SITHE GOREWAY-G12                             2025
SITHE GOREWAY-G13                             2025
SITHE GOREWAY-G15                             2025
SMOKY 2                                       2025
SOUTHGATE SF                                  2019
SPENCE                                        2019
STCLAIRCGS                                    2025
STEEPHILL                                     2025
STEWARTVLE                                    2025
STONE MILLS SF                                2019
SUMMERHAVEN                                   2019
TAOHSC                                        2025
TASARNIA                                      2025
TAWINDSOR                                     2025
TBAYBOWATER CTS                               2025
THOROLDCGS                                    2025
TUNISGS                                       2025
UMBATAFALLS                                   2025
UNDERWOOD                                     2019
UPPER WHITE RIVER                             2025
WELLS                                         2025
WEST LINCOLN NRWF                             2019
WESTWINDSOR                                   2025
WHITBYCGS                                     2025
WHITEDOG                                      2025
WINDSOR AIRPORT SF                            2019
WOLFE ISLAND                                  2019
YORKCGS-G1                                    2025
YORKCGS-G2                                    2025
ZURICH                                        2019

In [19]:
import pandas as pd

# If any DataFrame uses a 'generator' column instead of index:
for df in [df_p_max, df_min_output, df_results, df_ramps, cost_df, commission_year_df]:
    if 'generator' in df.columns:
        df.set_index('generator', inplace=True)

# 1) Combine all parameter DataFrames along columns
df_all_params = pd.concat([df_p_max, df_min_output, df_results, df_ramps, cost_df, commission_year_df], axis=1)
df_all_params.index.name = 'Generator'

# 3) Inspect the combined DataFrame
df_all_params

# 4) Save to CSV
output_path = "../Data/GeneratorParamaters.csv"
df_all_params.to_csv(output_path)

print(f"Combined parameters saved to {output_path}")

Combined parameters saved to ../Data/GeneratorParamaters.csv